pipeline {
    agent any

    stages {
        stage('Build Image') {
            steps {
                sh 'docker build -t pawanitzone/apache-html-web:${version} declarative/apache-html-web/.'
            }
        }
        stage("Deploy Artifact") {
           steps{
             script{
              withDockerRegistry(credentialsId: 'dockerhublogin') {
                 sh 'docker push pawanitzone/apache-html-web:${version}'
              }
             }
           }
         }
        stage('Remove docker image from jenkin host'){
            steps{
             sh 'docker rmi pawanitzone/apache-html-web:${version}'
            }
        }
    }
}
