pipeline {
    agent any

    stages {
        stage('Build Image') {
            steps {
                sh 'docker build -t apache-html-web:${version} declarative/apache-html-web/Dockerfile'
            }
        }
        //stage('')
    }
}