pipeline {
    agent any

    stages {
        stage('Build Image') {
            steps {
                sh 'sudo docker build -t apache-html-web:${version} declarative/apache-html-web/.'
            }
        }
        stage("Deploy Artifact") {
           steps{
             script{
              withDockerRegistry(credentialsId: 'dockerhublogin', url: 'https://hub.docker.com/') {
                 sh 'sudo docker push -t apache-html-web:${version}'
              }
             }
           }
         }
    }
}
